/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ariadnext.idcheckio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ReportResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-16T12:14:28.841+01:00")
public class ReportResponse   {
  @SerializedName("uid")
  private String uid = null;

  @SerializedName("analysisRefUid")
  private String analysisRefUid = null;

  @SerializedName("report")
  private String report = null;

  public ReportResponse uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * uid
   * @return uid
  **/
  @ApiModelProperty(example = "null", required = true, value = "uid")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public ReportResponse analysisRefUid(String analysisRefUid) {
    this.analysisRefUid = analysisRefUid;
    return this;
  }

   /**
   * analysisRefUid
   * @return analysisRefUid
  **/
  @ApiModelProperty(example = "null", required = true, value = "analysisRefUid")
  public String getAnalysisRefUid() {
    return analysisRefUid;
  }

  public void setAnalysisRefUid(String analysisRefUid) {
    this.analysisRefUid = analysisRefUid;
  }

  public ReportResponse report(String report) {
    this.report = report;
    return this;
  }

   /**
   * Pdf report (base64 encoded)
   * @return report
  **/
  @ApiModelProperty(example = "null", value = "Pdf report (base64 encoded)")
  public String getReport() {
    return report;
  }

  public void setReport(String report) {
    this.report = report;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportResponse reportResponse = (ReportResponse) o;
    return Objects.equals(this.uid, reportResponse.uid) &&
        Objects.equals(this.analysisRefUid, reportResponse.analysisRefUid) &&
        Objects.equals(this.report, reportResponse.report);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, analysisRefUid, report);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportResponse {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    analysisRefUid: ").append(toIndentedString(analysisRefUid)).append("\n");
    sb.append("    report: ").append(toIndentedString(report)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

