/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ariadnext.idcheckio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * TaskResponse
 */

public class TaskResponse   {
  @SerializedName("uid")
  private String uid = null;

  @SerializedName("isWithProgress")
  private Boolean isWithProgress = false;

  @SerializedName("accepted")
  private Long accepted = null;

  @SerializedName("started")
  private Long started = null;

  @SerializedName("ended")
  private Long ended = null;

  @SerializedName("lastProgress")
  private Long lastProgress = null;

  @SerializedName("percentage")
  private Integer percentage = null;

  @SerializedName("redirectUrl")
  private String redirectUrl = null;

  @SerializedName("message")
  private String message = null;

  public TaskResponse uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * analysisRefUid
   * @return uid
  **/
  @ApiModelProperty(example = "null", required = true, value = "analysisRefUid")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public TaskResponse isWithProgress(Boolean isWithProgress) {
    this.isWithProgress = isWithProgress;
    return this;
  }

   /**
   * task with progress
   * @return isWithProgress
  **/
  @ApiModelProperty(example = "null", value = "task with progress")
  public Boolean getIsWithProgress() {
    return isWithProgress;
  }

  public void setIsWithProgress(Boolean isWithProgress) {
    this.isWithProgress = isWithProgress;
  }

  public TaskResponse accepted(Long accepted) {
    this.accepted = accepted;
    return this;
  }

   /**
   * task accepted date
   * @return accepted
  **/
  @ApiModelProperty(example = "null", value = "task accepted date")
  public Long getAccepted() {
    return accepted;
  }

  public void setAccepted(Long accepted) {
    this.accepted = accepted;
  }

  public TaskResponse started(Long started) {
    this.started = started;
    return this;
  }

   /**
   * task started date
   * @return started
  **/
  @ApiModelProperty(example = "null", value = "task started date")
  public Long getStarted() {
    return started;
  }

  public void setStarted(Long started) {
    this.started = started;
  }

  public TaskResponse ended(Long ended) {
    this.ended = ended;
    return this;
  }

   /**
   * task ended date
   * @return ended
  **/
  @ApiModelProperty(example = "null", value = "task ended date")
  public Long getEnded() {
    return ended;
  }

  public void setEnded(Long ended) {
    this.ended = ended;
  }

  public TaskResponse lastProgress(Long lastProgress) {
    this.lastProgress = lastProgress;
    return this;
  }

   /**
   * last progress date
   * @return lastProgress
  **/
  @ApiModelProperty(example = "null", value = "last progress date")
  public Long getLastProgress() {
    return lastProgress;
  }

  public void setLastProgress(Long lastProgress) {
    this.lastProgress = lastProgress;
  }

  public TaskResponse percentage(Integer percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * percentage progress
   * @return percentage
  **/
  @ApiModelProperty(example = "null", value = "percentage progress")
  public Integer getPercentage() {
    return percentage;
  }

  public void setPercentage(Integer percentage) {
    this.percentage = percentage;
  }

  public TaskResponse redirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * redirect url
   * @return redirectUrl
  **/
  @ApiModelProperty(example = "null", value = "redirect url")
  public String getRedirectUrl() {
    return redirectUrl;
  }

  public void setRedirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }

  public TaskResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * message
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "message")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskResponse taskResponse = (TaskResponse) o;
    return Objects.equals(this.uid, taskResponse.uid) &&
        Objects.equals(this.isWithProgress, taskResponse.isWithProgress) &&
        Objects.equals(this.accepted, taskResponse.accepted) &&
        Objects.equals(this.started, taskResponse.started) &&
        Objects.equals(this.ended, taskResponse.ended) &&
        Objects.equals(this.lastProgress, taskResponse.lastProgress) &&
        Objects.equals(this.percentage, taskResponse.percentage) &&
        Objects.equals(this.redirectUrl, taskResponse.redirectUrl) &&
        Objects.equals(this.message, taskResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, isWithProgress, accepted, started, ended, lastProgress, percentage, redirectUrl, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskResponse {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    isWithProgress: ").append(toIndentedString(isWithProgress)).append("\n");
    sb.append("    accepted: ").append(toIndentedString(accepted)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    ended: ").append(toIndentedString(ended)).append("\n");
    sb.append("    lastProgress: ").append(toIndentedString(lastProgress)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

