/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ariadnext.idcheckio.api;

import com.ariadnext.idcheckio.invoker.ApiException;
import com.ariadnext.idcheckio.model.ErrorResponse;
import com.ariadnext.idcheckio.model.HealthResponse;
import com.ariadnext.idcheckio.model.UserResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdministrationApi
 */
public class AdministrationApiTest {

    private final AdministrationApi api = new AdministrationApi();

    
    /**
     * HTTP GET health
     *
     * GET server health (OK 200)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHealthTest() throws ApiException {
        // HealthResponse response = api.getHealth();

        // TODO: test validations
    }
    
    /**
     * HTTP GET user
     *
     * Get user informations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String acceptLanguage = null;
        // UserResponse response = api.getUser(acceptLanguage);

        // TODO: test validations
    }
    
}
