/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ariadnext.idcheckio.api;

import com.ariadnext.idcheckio.invoker.ApiException;
import com.ariadnext.idcheckio.model.ErrorResponse;
import com.ariadnext.idcheckio.model.ReportResponse;
import com.ariadnext.idcheckio.model.ResultResponse;
import com.ariadnext.idcheckio.model.TaskResponse;
import com.ariadnext.idcheckio.model.ImageRequest;
import com.ariadnext.idcheckio.model.MrzRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnalysisApi
 */
public class AnalysisApiTest {

    private final AnalysisApi api = new AnalysisApi();

    
    /**
     * HTTP GET report (demo)
     *
     * Get a pdf report (base64 encoded) (demo)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReportTest() throws ApiException {
        String analysisRefUid = null;
        String acceptLanguage = null;
        // ReportResponse response = api.getReport(analysisRefUid, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * HTTP GET result
     *
     * Get result controls
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResultTest() throws ApiException {
        String analysisRefUid = null;
        String acceptLanguage = null;
        Boolean rectoImageCropped = null;
        Boolean faceImageCropped = null;
        Boolean signatureImageCropped = null;
        // ResultResponse response = api.getResult(analysisRefUid, acceptLanguage, rectoImageCropped, faceImageCropped, signatureImageCropped);

        // TODO: test validations
    }
    
    /**
     * HTTP GET task
     *
     * Get task status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskTest() throws ApiException {
        String analysisRefUid = null;
        String acceptLanguage = null;
        Long wait = null;
        // TaskResponse response = api.getTask(analysisRefUid, acceptLanguage, wait);

        // TODO: test validations
    }
    
    /**
     * HTTP POST task image
     *
     * POST an image check task
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postImageTest() throws ApiException {
        ImageRequest body = null;
        Boolean asyncMode = null;
        String acceptLanguage = null;
        // ResultResponse response = api.postImage(body, asyncMode, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * HTTP POST task mrz
     *
     * POST a mrz check task
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postMrzTest() throws ApiException {
        MrzRequest body = null;
        Boolean asyncMode = null;
        String acceptLanguage = null;
        // ResultResponse response = api.postMrz(body, asyncMode, acceptLanguage);

        // TODO: test validations
    }
    
}
