/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.idcheckio;

import com.ApiException;
import org.junit.Test;

/**
 * API tests for SandboxApi
 */
public class SandboxApiTest {

    private final SandboxApi api = new SandboxApi();

    
    /**
     * HTTP GET image
     *
     * GET image
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImageTest() throws ApiException {
        String imageUid = null;
        String rawType = null;
        String face = null;
        String light = null;
        // B response = api.getImage(imageUid, rawType, face, light);

        // TODO: test validations
    }
    
    /**
     * HTTP GET images list
     *
     * GET images list
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImageListTest() throws ApiException {
        // ImageListResponse response = api.getImageList();

        // TODO: test validations
    }
    
    /**
     * HTTP GET mrz
     *
     * GET mrz
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMrzTest() throws ApiException {
        String mrzUid = null;
        // MrzResponse response = api.getMrz(mrzUid);

        // TODO: test validations
    }
    
    /**
     * HTTP GET mrz list
     *
     * GET mrz list
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMrzListTest() throws ApiException {
        // MrzListResponse response = api.getMrzList();

        // TODO: test validations
    }
    
}
